import * as dotenv from "dotenv";

dotenv.config();

export const {
  PORT,
  CORS_ORIGIN,
  NODE_ENV,

  MONGODB_URL,
  MONGODB_NAME,
  COMPANY_NAME,

  CLIENT_URL,

  ACCESS_TOKEN_SECRET,
  ACCESS_TOKEN_EXPIRY,
  REFRESH_TOKEN_SECRET,
  REFRESH_TOKEN_EXPIRY,

  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  CLOUDINARY_FOLDER_NAME,

  SMTP_HOST,
  SMTP_PORT,
  SMTP_USERNAME,
  SMTP_PASSWORD,
  SENDEREMAIL,

  EMAIL_VERIFICATION_TOKEN_EXPIRY,

  RAZORPAY_KEY_ID,
  RAZORPAY_KEY_SECRET,

  PAYPAL_CLIENT_ID,
  PAYPAL_SECRET,

  CANCELLATION_CHARGE,
} = process.env;
